### ISSUE TITLE
while take release build

### ISSUE THREAD

**Issue by capecomtest** [regulaforensics/flutter_face_api#1]
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String a2.a.b() (tried Java_a2_a_b and Java_a2_a_b__)
        at a2.a.b(Native Method)
        at a2.a.a(Unknown Source:0)
        at a2.l.b(Unknown Source:262)
        at a2.s.e(Unknown Source:91)
        at a2.b.run(:1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2022-02-08 10:27:06.450 4828-9477/? E/Camera3-OutputStream: returnBufferCheckedLocked: A frame is dropped for stream 2 frame 217 , due to buffer error.
2022-02-08 10:27:06.450 4828-9477/? E/Camera3-OutputStream: returnBufferCheckedLocked: A frame is dropped for stream 0 frame 217 , due to buffer error.

**Comment by vyakimchik** [comment]
Hi @capecomtest! Could you please confirm that this issue is reproduced in the latest version of our SDK?
