### ISSUE TITLE
App crash with Sending signal. PID: 4263 SIG: 9

### ISSUE THREAD

**Issue by vishw8878** [regulaforensics/flutter_face_api#24]
This all happen when we intialize   **FACESDK.INIT()**

E/AndroidRuntime( 4263): FATAL EXCEPTION: pool-27-thread-1
E/AndroidRuntime( 4263): Process: MY-BUNDLE-ID, PID: 4263
E/AndroidRuntime( 4263): java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime( 4263): 	at com.regula.facesdk.api.h.a(Unknown Source:13)
E/AndroidRuntime( 4263): 	at com.regula.facesdk.api.r.a(Unknown Source:9)
E/AndroidRuntime( 4263): 	at com.regula.facesdk.FaceSDK.a(Unknown Source:5)
E/AndroidRuntime( 4263): 	at com.regula.facesdk.FaceSDK.$r8$lambda$uyif4tqPZWyLsUMqQrFaBZrlVUM(Unknown Source:0)
E/AndroidRuntime( 4263): 	at com.regula.facesdk.FaceSDK$$ExternalSyntheticLambda3.run(Unknown Source:6)
E/AndroidRuntime( 4263): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 4263): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 4263): 	at java.lang.Thread.run(Thread.java:919)

**Comment by vishw8878** [comment]
Curently use Java SDk 19.0.2

**Comment by vishw8878** [comment]
finally, it's done !! 
You just have to add both dependency in your pubspec file.

  flutter_face_api: ^5.1.6
  flutter_face_core: ^5.1.0
