### ISSUE TITLE
[BR] java.lang.NoSuchMethodError after picking face

### ISSUE THREAD

**Issue by agnamc9** [regulaforensics/flutter_face_api#9]
Hello 

I had this error after picking face

```
java.lang.NoSuchMethodError: No virtual method getBuffer()Ljava/lang/String; in class Lcom/regula/common/http/RequestResponseData; or its super classes (declaration of 'com.regula.common.http.RequestResponseData' appears in /data/app/~~NnKBJyveut-8eNiSwg0D7w==/com.panelyscash.app-z4DonkqtApGsuRD3ENZ9wA==/base.apk!classes7.dex)
E/AndroidRuntime(31205): 	at com.regula.facesdk.service.i$b.run(Unknown Source:136)
E/AndroidRuntime(31205): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(31205): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(31205): 	at java.lang.Thread.run(Thread.java:923)
I/ExceptionHandle(31205): at com.regula.facesdk.service.i$b.run(Unknown Source:136)
I/ExceptionHandle(31205): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/ExceptionHandle(31205): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/ExceptionHandle(31205): at java.lang.Thread.run(Thread.java:923)
```

I use ```flutter_face_api: ^3.0.0```

**Comment by sethuram11** [comment]
i am using 6.2.3 and i have the same response for low end device like moto e6s  and after face scanning app will crash before the response.
